name: yacht

services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    restart: always

volumes:
  yacht:
